name: Upload Glue Script to S3

on:
  workflow_dispatch:

jobs:
  upload-script:
    name: Upload Glue script1.py to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload script1.py to S3
        run: |
          aws s3 cp Notebooks/script1.py s3://aws-glue-assets-573509103457-us-east-1/scripts/script1.py
