name: Glue CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  sync-glue-visual-jobs:
    name: Sync Visual Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install boto3
        run: pip install boto3

      - name: Configure AWS dev profile
        run: |
          mkdir -p ~/.aws
          echo "[dev]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.SRC_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.SRC_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Configure AWS prod profile
        run: |
          echo "[prod]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.DST_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.DST_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Run Visual Job Sync
        run: |
          python3 glue_ci/sync.py \
            --src-profile dev \
            --src-region us-east-1 \
            --dst-profile prod \
            --dst-region us-east-1 \
            --src-job-names ETL-Job \
            --config-path glue_ci/mapping.json \
            --skip-prompt

  upload-notebook-scripts:
    name: Upload Notebooks/*.py
    runs-on: ubuntu-latest
    needs: sync-glue-visual-jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for PROD
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Glue Notebook Scripts to S3
        run: |
          for file in Notebooks/*.py; do
            filename=$(basename "$file")
            echo "Uploading notebook script $filename"
            aws s3 cp "$file" "s3://aws-glue-assets-573509103457-us-east-1/scripts/$filename"
          done
