name: Deploy and Sync Glue Jobs

on:
  workflow_dispatch:

jobs:
  glue-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install boto3 and jq
        run: |
          pip install boto3
          sudo apt-get update && sudo apt-get install -y jq

      - name: Configure AWS source profile
        run: |
          mkdir -p ~/.aws
          echo "[dev]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.SRC_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.SRC_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Configure AWS destination profile
        run: |
          echo "[prod]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.DST_AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.DST_AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Sync Glue Visual Jobs
        run: |
          python3 glue_ci/sync.py \
            --src-profile dev \
            --src-region us-east-1 \
            --dst-profile prod \
            --dst-region us-east-1 \
            --src-job-names ETL-Job \
            --config-path glue_ci/mapping.json \
            --skip-prompt

      - name: Assume role in PROD for classic jobs
        id: assume
        run: |
          CREDS=$(aws sts assume-role \
            --role-arn "${{ secrets.ASSUME_ROLE_PROD_ARN }}" \
            --role-session-name glue-json-deploy)
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Deploy Glue Notebooks (.json)
        run: |
          for file in Notebooks/*.json; do
            job_name=$(basename "$file" .json)
            echo "Procesando job $job_name desde $file"
            if aws glue get-job --job-name "$job_name" >/dev/null 2>&1; then
              echo "Actualizando job existente: $job_name"
              aws glue update-job --job-name "$job_name" --job-update file://$file
            else
              echo "Creando nuevo job: $job_name"
              aws glue create-job --name "$job_name" --cli-input-json file://$file
            fi
          done

      - name: Upload Notebook Scripts (.py)
        run: |
          for file in Notebooks/*.py; do
            filename=$(basename "$file")
            aws s3 cp "$file" "s3://bucketprueba-produccion/scripts/$filename"
          done
